apiVersion: v1
kind: Service
metadata:
  name: secretsanta
  namespace: secretsanta
  labels:
    app: secretsanta
  name: secretsanta
spec:
  type: NodePort
  ports:
  - name: "secretsanta-service"
    port: 5000
    targetPort: 5432
    nodePort: 31002
  selector:
    app: secretsanta
  
